### ISSUE TITLE
Support installing Galaxy requirements

### ISSUE THREAD

**Issue by almereyda** [haxorof/docker-ansible-lint#263]
This image is used in the GitLab CI component https://gitlab.com/to-be-continuous/ansible for linting Ansible playbooks.

Unfortunately it does not install the roles and collections from `requirements.yml`, which has some statements fail in CI.

Running `ansible-lint` locally with Galaxy requirements installed does not show the behaviour.

**Comment by almereyda** [comment]
`ansible-galaxy` is installed in the container, so can be used during a CI run.

**Comment by haxorof** [comment]
Could you tell me in what way you would like to provide an galaxy requirements file to the container in way the would make your integration easy?

**Comment by haxorof** [comment]
@almereyda I just had a look at ansible-lint and itself already do install dependencies via ansible-galaxy and automatically detect requirements.yml files since 2020 according to PR merged back then. You can also see this in the verbose output of ansible-lint, e.g:
```
...
INFO     Running ansible-galaxy collection install -v -r /mnt/requirements.yml
INFO     Running ansible-galaxy role install -r /mnt/tests/requirements.yml -v --roles-path /root/.cache/ansible-compat/226768/roles
...
```
Having similar in my image when running it before ansible-lint feels a bit unnecessary now.

**Comment by almereyda** [comment]
This had come up in

- [[Ansible Lint] Missing requirements (#15) · Issues · to be continuous... / Ansible · GitLab](https://gitlab.com/to-be-continuous/ansible/-/issues/15)

Somewhat an extra call to the binary is needed there. The documentation confirms your observation:

- [Dependencies and requirements - Using - Ansible Lint Documentation](https://ansible.readthedocs.io/projects/lint/usage/#dependencies-and-requirements)

It would be useful for me to reproduce the CI error condition locally with a direct call to an ephemeral container. Is this maybe related to cases, in which an absolute or relative path is given to the playbook, but the requirements are somewhat missed?

Will report back, when I know more.

**Comment by almereyda** [comment]
The conclusion from [the analysis](https://gitlab.com/to-be-continuous/ansible/-/merge_requests/66#note_2268258675) is, that requirements do not appear to be picked up, if the playbook is called in another directory than the present working directory.

**Comment by haxorof** [comment]
Just based on what I read in your analysis .ansible-lint is picked up in the root directory of your repository but not the requirements files under src that directory is not part of the ansible-lint list in the documentation and is relative to working directory from where you run ansible-lint, it does not consider any relative location to the path specified for analysis unfortunately: https://ansible.readthedocs.io/projects/lint/usage/#dependencies-and-requirements

**Comment by almereyda** [comment]
Yes, thanks. This additional reference makes it a lot more clear. After writing my prior message, I had also concluded that this was instead worth an issue at upstream.

Let me close this as _won't fix_, since we need to deal with this rather up- or downstream to this project.
